package com.handybook.handybook.core.constant;

public class BundleKeys {

    public static final String ACTIVITY = "activity";
    public static final String BOOKING = "booking";
    public static final String BOOKINGS = "bookings";
    public static final String BOOKING_CANCELLATION_DATA = "booking_cancellation_data";
    public static final String BOOKING_ID = "booking_id";
    public static final String BOOKING_PHONE = "booking_phone";
    public static final String BOOKING_RATE_PRO_NAME = "prof";
    public static final String CANCELLED_BOOKING = "cancelled_booking";
    public static final String CANCEL_RECURRING_BOOKING_URL = "cancel_recurring_booking_url";
    public static final String DEEPLINK = "deep_link";
    public static final String FOR_VOUCHER = "for_voucher";
    public static final String HELP_CENTER_URL = "help_center_url";
    public static final String HELP_ID = "help_article_id";
    public static final String HELP_LINK_TYPE = "help_link_type";
    public static final String HELP_NODE = "help_node";
    public static final String HELP_NODE_ID = "help_node_id";
    public static final String IS_FROM_BOOKING_FLOW = "is_from_booking_flow";
    public static final String IS_IN_NESTED_SCROLLVIEW = "is_in_nested_scrollview";
    public static final String PATH = "path";
    public static final String POST_OPTIONS = "post_options";
    public static final String PRERATE_PRO_INFO = "prerate_pro_info";
    public static final String PROVIDER_ID = "provider_id";
    public static final String PROVIDER_NAME = "provider_name";
    public static final String PRO_JOB_STATUS = "pro_statuses";
    public static final String PRO_TEAM = "pro_team";
    public static final String PRO_TEAM_CATEGORY = "pro_team_category";
    public static final String PRO_TEAM_CATEGORY_TYPE = "pro_team_category_type";
    public static final String PRO_TEAM_EDIT = "pro_team_edit";
    public static final String PRO_TEAM_PRO = "pro_team_pro";
    public static final String PRO_TEAM_PRO_ID = "pro_team_pro_id";
    public static final String PRO_TEAM_PRO_PREFERENCE = "pro_team_pro_preference";
    public static final String EDIT_PRO_TEAM_PREFERENCE_ACTION_TYPE
            = "edit_pro_team_preference_action_type";
    public static final String RECURRING_BOOKING = "recurring_booking";
    public static final String RECURRING_PLAN = "recurring_plan";
    public static final String RECURRING_PLANS = "recurring_plans";
    public static final String REFERRAL_PAGE_SOURCE = "referral_page_source";
    public static final String REFERRAL_HIDE_TOOLBAR = "referral_hide_toolbar";
    public static final String REFERRAL_DESCRIPTOR = "referral_descriptor";
    public static final String PRO_REFERRAL = "pro_referral";
    public static final String RESCHEDULE_ALL = "reschedule_all";
    public static final String RESCHEDULE_BOOKING = "reschedule_booking";
    public static final String RESCHEDULE_NEW_DATE = "reschedule_new_date";
    public static final String RESCHEDULE_NOTICE = "reschedule_notice";
    public static final String RESCHEDULE_PRICE_TABLE = "reschedule_price_table";
    public static final String RESCHEDULE_IS_INSTANT_BOOK_ENABLED = "reschedule_instant_book";
    public static final String RESCHEDULE_TYPE = "reschedule_type";
    public static final String SERVICES = "services";
    public static final String SHOW_TIPS = "show_tips";
    public static final String TARGET_URL = "target_url";
    public static final String TITLE = "title";
    public static final String UPDATED_BOOKING = "updated_booking";
    public static final String USER_ID = "user_id";
    public static final String ZIP = "zip";
    public static final String PRO_MESSAGES_VIEW_MODEL = "pro_messages_view_model";
    public static final String PRO_RATING = "pro_rating";
    public static final String PROVIDER = "provider";
    public static final String PRO_RATING_REASONS_QUEUE = "pro_rating_reasons_queue";
    public static final String IMPROVEMENT_FEEDBACK = "improvement_feedback";
    public static final String RECOMMENDED_PROVIDERS = "recommended_providers";
    public static final String PRO_AVAILABILITY = "pro_availability";
    public static final String EVENT_CONTEXT = "event_context";
    public static final String BOOKING_FLOW_STARTED = "BOOKING_FLOW_STARTED";
    public static final String SHOW_PROGRESS = "SHOW_PROGRESS";
    public static final String PROGRESS = "PROGRESS";
    public static final String PAGE_SOURCE = "page_source";
    public static final String SHOULD_SHOW_TOOLBAR = "should_show_toolbar";

}
