package com.handybook.handybook.core.constant;

public enum PrefsKey
{
    USER("USER_OBJ"),
    BOOKING_REQUEST("BOOKING_REQ"),
    BOOKING_QUOTE("BOOKING_QUOTE"),
    BOOKING_TRANSACTION("BOOKING_TRANS"),
    BOOKING_POST("BOOKING_POST"),
    BOOKING_PROMO_TAB_COUPON("BOOKING_PROMO_TAB_COUPON"),
    STATE_BOOKING_CLEANING_EXTRAS_SELECTION("STATE_BOOKING_CLEANING_EXTRAS_SEL"),
    CACHED_SERVICES("CACHED_SERVICES"),
    APP_BLOCKED("APP_BLOCKED"),
    APP_BLOCKED_LAST_CHECK("APP_BLOCKED_LAST_CHECK"),
    APP_FIRST_RUN("APP_FIRST_RUN"),
    APP_ONBOARD_SHOWN("APP_ONBOARD_SHOWN"),
    APP_LAUNDRY_INFO_SHOWN("APP_LAUNDRY_INFO_SHOWN"),
    ENVIRONMENT_PREFIX("ENVIRONMENT_PREFIX"),
    DISPLAYED_SPLASH_PROMOS("DISPLAYED_SPLASH_PROMOS"),
    ACCEPTED_SPLASH_PROMOS("ACCEPTED_SPLASH_PROMOS"),
    CONFIGURATION("CONFIGURATION"),
    BOOKING_FINALIZE_PAYLOAD("BOOKING_FINALIZE_PAYLOAD"),
    EVENT_LOG_BUNDLES("EVENT_LOG_BUNDLES"),
    EVENT_LOG_BUNDLES_TO_SEND("EVENT_LOG_BUNDLES_TO_SEND"),
    APP_FIRST_LAUNCH("FIRST_LAUNCH"),
    LOG_SESSION("LOG_SESSION"),
    INSTALLATION_ID("INSTALLATION_ID"),
    ZIP("ZIP"),
    EMAIL("EMAIL"),
    REFERRAL_DIALOG_LAST_REQUESTED_TIME_MS("REFERRAL_DIALOG_LAST_REQUESTED_TIME_MS");

    private String mKey;

    PrefsKey(String key)
    {
        mKey = key;
    }

    public String getKey()
    {
        return this.mKey;
    }

    @Override
    public String toString()
    {
        return this.getKey();
    }
}
